apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgres.dboperator.p16n.org
spec:
  group: dboperator.p16n.org
spec:
  group: dboperator.p16n.org
  names:
    kind: Postgres
    categories:
    - database-entity-operator
    listKind: PostgresList
    plural: postgres
    singular: postgres
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: PostgresUser is the Schema for the postgresusers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PostgresSpec defines the desired state of Postgres
            properties:
              database:
                type: string
              dropOnDelete:
                type: boolean
              extensions:
                items:
                  type: string
                type: array
              schemas:
                items:
                  type: string
                type: array
            required:
            - database
            type: object
        type: object
