apiVersion: v1
kind: Config
preferences: {}

clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://localhost
    name: test

users:
  - name: test
    user:
      password: test
      username: test

contexts:
  - context:
      cluster: test
      user: test
    name: test

current-context: test
