name: continuous integration
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: |
          python -m pip install -U pip
          pip install tox tox-gh-actions
      - name: run tests
        run: |
          mkdir -p ~/.kube
          cp .ci/kubeconfig.yaml ~/.kube/config
          tox

  crd_tests:
    name: crd validity tests
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
        kubernetes_version: ['1.19.6']
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: somePassword
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
        run: |
          set -x
          docker version
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: setup py37
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: timomo
        env:
          POSTGRES_HOST: "127.0.0.1"
          POSTGRES_DEFAULT_DATABASE: postgres
          POSTGRES_PASS: somePassword
          POSTGRES_USER: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          echo $USER
          psql postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/{POSTGRES_DEFAULT_DATABASE} -c 'CREATE DATABASE rudo;'
