name: continuous integration
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: |
          python -m pip install -U pip
          pip install tox tox-gh-actions
      - name: run tests
        run: |
          mkdir -p ~/.kube
          cp .ci/kubeconfig.yaml ~/.kube/config
          tox

  crd_tests:
    name: crd validity tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes_version: ['1.19.6']

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  python:3.8-slim-bullseye

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: somePassword
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: copy kubeconfig
        run: |
          mkdir -p ~/.kube
          cp .ci/kubeconfig.yaml ~/.kube/config
      - name: setup minikube
        id: minikube
        uses: manusa/actions-setup-minikube@v2.4.3
        with:
          minikube version: v1.25.1
          kubernetes version: v${{ matrix.kubernetes_version }}
      - name: apply crd
        run: |
          kubectl apply -f postgres_crd.yaml
          kubectl apply -f postgresuser_crd.yaml
      - name: install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: run kopf tests
        env:
          POSTGRES_HOST: postgres
          POSTGRES_DEFAULT_DATABASE: postgres
          POSTGRES_PASS: somePassword
          POSTGRES_USER: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          tox -e e2e
